# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    name: GCC ${{matrix.gcc}} (CrossSection:${{matrix.cross_section}}, TBB:${{matrix.parallelization}})
    timeout-minutes: 45
    strategy:
      matrix:
        cross_section: [ON]
        parallelization: [OFF, ON]
        os: [ubuntu-24.04]
        gcc: [13, 14]
        include:
          - cross_section: OFF
            parallelization: ON
            os: ubuntu-24.04
            gcc: 14
          - cross_section: ON
            parallelization: ON
            os: ubuntu-22.04
            gcc: 11
    runs-on: ${{ matrix.os }}
    env:
      CC: gcc-${{ matrix.gcc }}
      CXX: g++-${{ matrix.gcc }}
    outputs:
      java_package_version_changed: ${{ steps.check_version.outputs.changed }}
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libgtest-dev libassimp-dev git libtbb-dev pkg-config libpython3-dev lcov
        python -m pip install -U trimesh pytest
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: 4.0.2
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Install Maven
      run: |
        sudo apt-get update
        sudo apt-get install -y maven
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build ${{matrix.parallelization}}
      if: matrix.parallelization != 'OFF'
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DMANIFOLD_STRICT=ON -DMANIFOLD_PYBIND=ON -DMANIFOLD_DEBUG=ON -DMANIFOLD_ASSERT=ON -DMANIFOLD_FLAGS=-UNDEBUG -DMANIFOLD_CROSS_SECTION=${{matrix.cross_section}} -DASSIMP_ENABLE=ON -DMANIFOLD_PAR=${{matrix.parallelization}} .. && make
    - name: Test ${{matrix.parallelization}}
      if: matrix.parallelization != 'OFF'
      run: |
        cd build/test
        ./manifold_test
    - name: Test Python bindings ${{matrix.parallelization}}
      if: matrix.parallelization != 'OFF' && matrix.cross_section == 'ON'
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/build/bindings/python
        python3 bindings/python/examples/run_all.py -e
        python3 -m pytest


    - name: test cmake consumer
      run: |
        mkdir build
        cd build
        sudo cmake --install .
        cd ..
        ./scripts/test-cmake.sh
    - name: Get version
      id: get_version
      run: echo "VERSION=$(cat bindings/java/version.txt)" >> $GITHUB_ENV
      shell: bash
    - name: Check if version has changed
      id: check_version
      shell: bash
      run: |
        if git diff --quiet HEAD~1 -- bindings/java/version.txt
        then
          echo "Version Unchanged!"
          echo "changed=false" >> "$GITHUB_OUTPUT"
        else
          echo "Version Changed!"
          echo "changed=true" >> "$GITHUB_OUTPUT"
        fi
    - name: Build Java package
      shell: bash
      run: |
        cd bindings/java

        BACKEND=""
        if [ "${{matrix.parallelization}}" = "OFF" ]; then
            BACKEND=""
        else
            BACKEND="-${{matrix.parallelization}}"
        fi

        mvn versions:set -DnewVersion=$(cat version.txt) --file pom.xml
        mvn package -Dos.classifier=linux$BACKEND-x86_64
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: manifold_java_bindings_linux_${{matrix.parallelization}}_${{env.VERSION}}
        path: bindings/java/target/*.jar

  build_wasm:
    name: WASM (TBB:${{matrix.parallelization}}, DEBUG:${{matrix.debug}})
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        parallelization: [OFF, ON]
        debug: [OFF, ON]
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get -y update
        DEBIAN_FRONTEND=noninteractive sudo apt install -y nodejs
    - uses: actions/checkout@v4
    - name: Setup WASM
      run: |
        # setup emscripten
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install 3.1.64
        ./emsdk activate 3.1.64
    - uses: jwlawson/actions-setup-cmake@v2
    - name: Build WASM ${{matrix.parallelization}}
      run: |
        source ./emsdk/emsdk_env.sh
        mkdir build
        cd build
        emcmake cmake -DCMAKE_BUILD_TYPE=MinSizeRel -DMANIFOLD_STRICT=ON -DMANIFOLD_PAR=${{matrix.parallelization}} -DMANIFOLD_USE_BUILTIN_TBB=ON -DMANIFOLD_DEBUG=${{matrix.debug}} -DMANIFOLD_ASSERT=${{matrix.debug}} .. && emmake make
    - name: Test WASM
      if: matrix.parallelization == 'OFF'
      run: |
        cd build/test
        node ./manifold_test.js
    - name: Run unit tests
      if: matrix.parallelization == 'OFF'
      run: |
        cd bindings/wasm
        npm ci
        npm run build
        npm test
    - name: Isolated npm smoke test
      if: matrix.parallelization == 'OFF'
      run: |
        set -ev -o pipefail
        cd bindings/wasm
        wasmpath=$(pwd)
        npmtestpath=../npmtest
        # Create an npm package.
        npm ci && npm pack
        # Install it in an empty directory.
        mkdir -p ${npmtestpath} && cd ${npmtestpath}
        npm install ${wasmpath}/manifold-3d*.tgz
        cp ${wasmpath}/test/fixtures/npm/* .
        # Positive case smoke test.
        npx manifold-cad ./unitSphere.mjs ./unitSphere.glb && echo "Positive smoke test succeeded"
        # Negative case smoke test.
        npx manifold-cad ./unitSphereNoManifoldImport.mjs ./unitSphereNoManifoldImport.glb || echo "Negative smoke test failed as expected"
    - name: Build manifoldCAD editor
      if: matrix.parallelization == 'OFF'
      run: |
        cd bindings/wasm
        npm run ci:editor
        npm run build:editor
    - name: Build WASM examples
      if: matrix.parallelization == 'OFF'
      run: |
        cd bindings/wasm/examples
        npm run ci:examples
        npm run build:examples
    - name: Build WASM documentation and site
      if: matrix.parallelization == 'OFF'
      run: |
        cd bindings/wasm
        npm run docs
        npm run public
    - name: Upload manifoldCAD editor, examples and documentation
      uses: actions/upload-artifact@v4
      if: github.event_name == 'push' && matrix.parallelization == 'OFF' && matrix.debug == 'OFF'
      with:
        name: wasmpublic
        path: bindings/wasm/public/
        retention-days: 90
        overwrite: true
    - name: Upload complete wasm build.
      uses: actions/upload-artifact@v4
      if: github.event_name == 'push' && matrix.parallelization == 'OFF' && matrix.debug == 'OFF'
      with:
        name: wasm
        path: bindings/wasm/
        retention-days: 90
        overwrite: true

  build_fuzzer:
    name: fuzzer
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get -y update
        DEBIAN_FRONTEND=noninteractive sudo apt install -y libgtest-dev clang
    - uses: actions/checkout@v4
    - uses: jwlawson/actions-setup-cmake@v2
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DMANIFOLD_STRICT=ON -DMANIFOLD_DEBUG=ON -DMANIFOLD_FUZZ=ON -DMANIFOLD_PYBIND=OFF -DCMAKE_CXX_COMPILER=clang++ ..
        make

  build_fuzzer_mac:
    name: fuzzer mac
    timeout-minutes: 30
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install common dependencies
      run: |
        brew install googletest
    - uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: 3.31.6
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DMANIFOLD_STRICT=ON -DMANIFOLD_DEBUG=ON -DMANIFOLD_FUZZ=ON -DMANIFOLD_PYBIND=OFF -DCMAKE_CXX_COMPILER=clang++ -DMANIFOLD_PAR=OFF ..
        ASAN_OPTIONS=detect_container_overflow=0 make

  build_windows:
    name: Windows (TBB:${{matrix.parallelization}}, SHARED:${{matrix.shared}})
    timeout-minutes: 30
    strategy:
      matrix:
        parallelization: [OFF, ON]
        shared: [OFF, ON]
    runs-on: windows-2025
    steps:
    - uses: actions/checkout@v4
    - uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: 4.0.2
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Build ${{matrix.parallelization}}
      shell: powershell
      run: |
        cmake . -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=${{matrix.shared}} -DMANIFOLD_STRICT=ON -DMANIFOLD_USE_BUILTIN_TBB=ON -DMANIFOLD_DEBUG=ON -DMANIFOLD_ASSERT=ON -DMANIFOLD_PAR=${{matrix.parallelization}} -A x64 -B build
        cd build
        cmake --build . --target ALL_BUILD --config Release
    - name: Test dll location
      if: matrix.shared == 'ON'
      shell: bash
      run: |
        ls ./build/lib/Release
        [ -f ./build/lib/Release/manifold.dll ]
        [ -f ./build/lib/Release/manifoldc.dll ]
    - name: Test
      shell: bash
      run: |
        cp ./build/lib/Release/* ./build/bin/Release
        cd build/bin/Release
        ./manifold_test.exe
        cd ../../
    - name: test cmake consumer
      run: |
        cd build
        cmake --install . --prefix ../install
        cd ..
        ./scripts/test-cmake.sh

  build_mxe:
    name: MXE (TBB:${{matrix.parallelization == 'ON'}})
    timeout-minutes: 30
    strategy:
      matrix:
        parallelization: [OFF, ON]
    runs-on: ubuntu-latest
    container: openscad/mxe-x86_64-gui:latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        mkdir build
        cd build
        export MXEDIR=/mxe
        export MXE_TARGETS=x86_64-w64-mingw32.static.posix
        export MXEDIR=$HOME/openscad_deps/mxe
        export MXETARGETDIR=$MXEDIR/usr/$MXE_TARGETS
        export PATH=/mxe/usr/bin:$PATH
        export CMAKE=$MXE_TARGETS-cmake
        $CMAKE -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DMANIFOLD_STRICT=ON -DMANIFOLD_PYBIND=OFF -DMANIFOLD_CBIND=ON -DMANIFOLD_DEBUG=ON -DMANIFOLD_PAR=${{matrix.parallelization}} .. && make

  build_mac:
    name: MacOS (TBB:${{matrix.parallelization == 'ON'}}, shared lib:${{matrix.shared == 'ON'}}, ${{matrix.os}})
    timeout-minutes: 30
    strategy:
      matrix:
        parallelization: [OFF, ON]
        shared: [OFF, ON]
        # macos-15-intel: intel
        # macos-latest: arm
        os: [macos-15-intel, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
    - name: Install Python 3.12
      run: |
        brew update
        brew install python@3.12
        curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    - name: Configure Python 3.12 Environment
      run: |
        echo "PATH=$(brew --prefix python@3.12)/bin:/opt/homebrew/opt/python@3.12/libexec/bin:$PATH" >> $GITHUB_ENV
    - name: Install common dependencies
      run: |
        python3 -m venv .venv
        brew install pkg-config assimp
    - name: Install TBB
      if: matrix.parallelization == 'ON'
      run: brew install tbb
    - name: Install Java and Maven
      run: |
        brew install openjdk@17
        export PATH="/usr/local/opt/openjdk@17/bin:$PATH"
        brew install --ignore-dependencies maven
        echo "JAVA_HOME=$(/usr/libexec/java_home -v 17)" >> $GITHUB_ENV
    - name: Check Java version
      run: java -version
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: 4.0.2
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=${{matrix.shared}} -DMANIFOLD_STRICT=ON -DMANIFOLD_DEBUG=ON -DMANIFOLD_ASSERT=ON -DMANIFOLD_PYBIND=ON -DASSIMP_ENABLE=ON -DMANIFOLD_PAR=${{matrix.parallelization}} .. && make
    - name: Test
      run: |
        cd build/test
        ./manifold_test
    - name: Find Libs
      run: |
        find . -name "*.dylib"
      shell: bash
    - name: Build Java package
      shell: bash
      run: |
        export PATH="/usr/local/opt/openjdk@17/bin:$PATH"
        cd bindings/java
        JAVA_PACKAGE_VERSION=$(cat version.txt)
        echo "JAVA_PACKAGE_VERSION=$JAVA_PACKAGE_VERSION" >> $GITHUB_ENV
        BACKEND=""
        if [ "${{matrix.parallelization}}" = "ON" ]; then
            BACKEND="-TBB"
        fi
        mvn versions:set -DnewVersion=$JAVA_PACKAGE_VERSION --file pom.xml
        mvn package -Dos.classifier=mac$BACKEND-x86_64
    - name: test cmake consumer
      run: |
        cd build
        sudo cmake --install .
        cd ..
        ./scripts/test-cmake.sh
    - name: test pkg-config consumer
      if: matrix.shared == 'ON'
      run: |
        LDFLAGS=-Wl,-rpath,/usr/local/lib ./scripts/test-pkgconfig.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: manifold_java_bindings_mac_${{matrix.parallelization}}_${{env.JAVA_PACKAGE_VERSION}}
        path: bindings/java/target/*.jar
    - name: Upload Surefire Reports
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: surefire-reports
        path: |
          bindings/java/target/surefire-reports
          bindings/java/target/*.dump
          bindings/java/target/*-jvmRun*.dump
          bindings/java/target/*.dumpstream

  build_mac_builtin_tbb:
    timeout-minutes: 30
    runs-on: macos-latest
    steps:
    - name: Install common dependencies
      run: |
        brew install googletest
        pip install trimesh pytest
    - uses: actions/checkout@v4
    - uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: 4.0.2
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DMANIFOLD_STRICT=ON -DMANIFOLD_USE_BUILTIN_TBB=ON -DMANIFOLD_DEBUG=ON -DMANIFOLD_ASSERT=ON -DMANIFOLD_PYBIND=OFF -DMANIFOLD_PAR=ON .. && make
    - name: Test
      run: |
        cd build/test
        ./manifold_test
        cd ../../
    - name: test cmake consumer
      run: |
        cd build
        sudo cmake --install .
        cd ..
        ./scripts/test-cmake.sh
        LDFLAGS=-Wl,-rpath,/usr/local/lib ./scripts/test-pkgconfig.sh

  build_mac_builtin_tbb_subdir:
    timeout-minutes: 30
    runs-on: macos-latest
    steps:
    - name: Install common dependencies
      run: |
        brew install googletest
        pip install trimesh pytest
    - uses: actions/checkout@v4
    - uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: 4.0.2
    - name: test cmake consumer
      run: |
        cd ..
        ./manifold/scripts/test-cmake-subdir.sh

  build_nix:
    timeout-minutes: 30
    strategy:
      matrix:
        variant: [manifold-none, manifold-tbb, manifold-js, manifold-js-tbb, manifold3d]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - run: nix build -L '.?submodules=1#${{matrix.variant}}'

  deploy_jars:
    runs-on: ubuntu-22.04
    needs: [build, build_mac]
    if: needs.build.outputs.java_package_version_changed == 'true'
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Install Maven
      run: |
        sudo apt-get update
        sudo apt-get install -y maven
    - name: Get version
      id: get_version
      run: echo "VERSION=$(cat bindings/java/version.txt)" >> $GITHUB_ENV
      shell: bash
    - name: Download Linux artifact
      uses: actions/download-artifact@v4
      with:
        name: manifold_java_bindings_linux_OFF_${{env.VERSION}}
        path: linux-jar
    - name: Download Linux TBB artifact
      uses: actions/download-artifact@v4
      with:
        name: manifold_java_bindings_linux_ON_${{env.VERSION}}
        path: linux-tbb-jar
    - name: Download Mac TBB artifact
      uses: actions/download-artifact@v4
      with:
        name: manifold_java_bindings_mac_ON_${{env.VERSION}}
        path: mac-tbb-jar
    - name: Deploy Jars
      shell: bash
      run: |
        VERSION=$(cat bindings/java/version.txt)
        linux_jar_file=linux-jar/manifold3d-$VERSION-linux-x86_64.jar
        linux_tbb_jar_file=linux-tbb-jar/manifold3d-$VERSION-linux-ON-x86_64.jar
        mac_tbb_jar_file=mac-tbb-jar/manifold3d-$VERSION-mac-TBB-x86_64.jar

        mvn versions:set -DnewVersion=$VERSION --file bindings/java/pom.xml
        mvn deploy:deploy-file \
          -DpomFile=bindings/java/pom.xml \
          -DrepositoryId=clojars \
          -Durl=https://clojars.org/repo \
          -DgroupId=com.github.madhephaestus \
          -DartifactId=manifold3d \
          -Dversion=$VERSION \
          -Dpackaging=jar \
          -Dfile=$linux_tbb_jar_file \
          -Dclassifier=linux-TBB-x86_64 \
          -Dfiles=$mac_tbb_jar_file,$linux_jar_file \
          -Dclassifiers=mac-TBB-x86_64,linux-x86_64 \
          -Dtypes=jar,jar \
          --settings=bindings/java/settings.xml
      env:
        CLOJARS_PASSPHRASE: ${{ secrets.CLOJARS_PASSPHRASE }}
        CLOJARS_TOKEN: ${{ secrets.CLOJARS_TOKEN }}