# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master, main ]

jobs:
  build_linux:
    timeout-minutes: 45
    strategy:
      matrix:
        cuda_support: [OFF]
        parallel_backend: [NONE]
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false || startsWith(github.ref, 'refs/tags/')
    outputs:
      java_package_version_changed: ${{ steps.check_version.outputs.changed }}
    container:
      image: docker://nvidia/cuda:12.0.1-devel-ubuntu22.04
    steps:
    - name: Install dependencies
      run: |
        apt-get -y update
        DEBIAN_FRONTEND=noninteractive apt install -y libomp-dev libassimp-dev git libtbb-dev pkg-config libpython3-dev python3 python3-distutils python3-pip lcov
        pip install trimesh
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 2
    - uses: jwlawson/actions-setup-cmake@v1.12
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
    - name: Install Maven
      run: |
        apt-get update
        apt-get install -y maven
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build ${{matrix.backend}}
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DASSIMP_ENABLE=ON -DBUILD_SHARED_LIBS=ON -DMANIFOLD_DEBUG=ON -DMANIFOLD_EXPORT=ON -DMANIFOLD_PAR=${{matrix.parallel_backend}} -DCMAKE_POLICY_VERSION_MINIMUM=3.5 .. && make
    - name: Get version
      id: get_version
      run: echo "VERSION=$(cat bindings/java/version.txt)" >> $GITHUB_ENV
      shell: bash
    - name: Check if version has changed
      id: check_version
      shell: bash
      run: |
        if git diff --quiet HEAD~1 -- bindings/java/version.txt
        then
          echo "Version Unchanged!"
          echo "changed=false" >> "$GITHUB_OUTPUT"
        else
          echo "Version Changed!"
          echo "changed=true" >> "$GITHUB_OUTPUT"
        fi
    - name: Build Java package
      shell: bash
      run: |
        cd bindings/java

        BACKEND=""
        if [ "${{matrix.parallel_backend}}" = "NONE" ] && [ "${{matrix.cuda_support}}" = "ON" ]; then
            BACKEND="-cuda"
        elif [ "${{matrix.parallel_backend}}" = "NONE" ] && [ "${{matrix.cuda_support}}" = "OFF" ]; then
            BACKEND=""
        elif [ "${{matrix.cuda_support}}" = "ON" ]; then
            BACKEND="-${{matrix.parallel_backend}}-cuda"
        else
            BACKEND="-${{matrix.parallel_backend}}"
        fi

        mvn versions:set -DnewVersion=$(cat version.txt) --file pom.xml
        mvn package -Dos.classifier=linux$BACKEND-x86_64
        find  ./target/classes/ -name "*.class" -delete
    # - name: Test ${{matrix.parallel_backend}} with CUDA ${{matrix.cuda_support}}
    #   # note that the test for CUDA backend does not really test CUDA, as we
    #   # don't have CUDA GPU on GitHub Action
    #   if: matrix.parallel_backend != 'NONE' || matrix.cuda_support != 'OFF'
    #   run: |
    #     export PYTHONPATH=$PYTHONPATH:$(pwd)/build/bindings/python
    #     cd build/test
    #     ./manifold_test
    #- name: Coverage Report
    #  # only do code coverage for default sequential backend, it seems that TBB
    #  # backend will cause failure
    #  # perhaps issue related to invalid memory access?
    #  if: matrix.parallel_backend == 'NONE' && matrix.cuda_support == 'OFF'
    #  run: |
    #    cd build
    #    cmake -DOUTPUT_TO_BIN=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DMANIFOLD_PAR=${{matrix.parallel_backend}} -DMANIFOLD_USE_CUDA=${{matrix.cuda_support}} -DCODE_COVERAGE=ON .. && make
    #    lcov --capture --initial --directory . --output-file ./code_coverage_init.info
    #    cd bin
    #    ./manifold_test
    #    cd ../
    #    lcov --capture --directory . --output-file ./code_coverage_test.info
    #    lcov --add-tracefile ./code_coverage_init.info --add-tracefile ./code_coverage_test.info --output-file ./code_coverage_total.info
    #    lcov --remove ./code_coverage_total.info '/usr/*' '*/third_party/*' '*/test/*' '*/extras/*' '*/bindings/*' --output-file ./code_coverage.info
    - uses: codecov/codecov-action@v2
      with:
        files: build/code_coverage.info
        fail_ci_if_error: false
        name: ${{matrix.parallel_backend}}-${{matrix.cuda_support}}
    - name: Upload artifact
      uses: actions/upload-artifact@v4  # updated from v3
      with:
        name: manifold_java_bindings_linux_${{env.VERSION}}
        path: bindings/java/target/classes/

  build_mac:
    timeout-minutes: 30
    strategy:
      matrix:
        parallel_backend: [NONE]
    runs-on: macos-14
    if: github.event.pull_request.draft == false || startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Install Python 3.12
      run: |
        brew update
        brew install python@3.12
        curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    - name: Configure Python 3.12 Environment
      run: |
        echo "PATH=$(brew --prefix python@3.12)/bin:/opt/homebrew/opt/python@3.12/libexec/bin:$PATH" >> $GITHUB_ENV
    - name: Install common dependencies
      run: |
        python3 -m venv .venv
        brew install pkg-config assimp
        # pip install trimesh
#    - name: Install Java and Maven
#      run: |
#        brew install openjdk@21
#        export PATH="/usr/local/opt/openjdk@21/bin:$PATH"
#        brew install --ignore-dependencies maven
#        echo "JAVA_HOME=$(/usr/libexec/java_home -v 21)" >> $GITHUB_ENV
    - name: Install Java and Maven
      run: |
        brew install openjdk@21
        export PATH="$(brew --prefix openjdk@21)/bin:$PATH"
        echo "PATH=$(brew --prefix openjdk@21)/bin:$PATH" >> $GITHUB_ENV
        brew install --ignore-dependencies maven
        echo "JAVA_HOME=$(brew --prefix openjdk@21)" >> $GITHUB_ENV
    - name: Check Java version
      run: java -version
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 2
    - uses: jwlawson/actions-setup-cmake@v1.12
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DASSIMP_ENABLE=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_POLICY_VERSION_MINIMUM=3.5 .. && make
      shell: bash
    - name: Find Libs
      run: |
        find . -name "*.dylib"
      shell: bash
    - name: Build Java package
      shell: bash
      run: |
        export PATH="/usr/local/opt/openjdk@21/bin:$PATH"
        cd bindings/java
        JAVA_PACKAGE_VERSION=$(cat version.txt)
        echo "JAVA_PACKAGE_VERSION=$JAVA_PACKAGE_VERSION" >> $GITHUB_ENV
        mvn versions:set -DnewVersion=$JAVA_PACKAGE_VERSION --file pom.xml
        mvn package -Dos.classifier=mac-arm64
        find  ./target/classes/ -name "*.class" -delete
    # - name: Test
    #   run: |
    #     cd build/test
    #     ./manifold_test
    - name: Upload artifact
      uses: actions/upload-artifact@v4  # updated from v3
      with:
        name: manifold_java_bindings_mac_${{env.JAVA_PACKAGE_VERSION}}
        path: bindings/java/target/classes/
    - name: Find Libs
      if: failure() # This step will run only if the previous steps failed
      run: |
        find . -name "*.dylib"
      shell: bash
    - name: Upload Surefire Reports
      if: failure() # This step will run only if the previous steps failed
      uses: actions/upload-artifact@v4  # updated from v3
      with:
        name: surefire-reports
        path: |
          /Users/runner/work/manifold/manifold/bindings/java/target/surefire-reports
          /Users/runner/work/manifold/manifold/bindings/java/target/*.dump
          /Users/runner/work/manifold/manifold/bindings/java/target/*-jvmRun*.dump
          /Users/runner/work/manifold/manifold/bindings/java/target/*.dumpstream

  deploy_jars:
    runs-on: ubuntu-latest
    needs: [ build_mac]
    container:
      image: docker://nvidia/cuda:12.0.1-devel-ubuntu22.04
    steps:
    - name: Install dependencies
      run: |
        apt-get -y update
        DEBIAN_FRONTEND=noninteractive apt install -y libomp-dev libassimp-dev git libtbb-dev pkg-config libpython3-dev python3 python3-distutils python3-pip lcov
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 2
    - uses: jwlawson/actions-setup-cmake@v1.12
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build C code
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DASSIMP_ENABLE=ON -DBUILD_SHARED_LIBS=ON -DMANIFOLD_DEBUG=ON -DMANIFOLD_EXPORT=ON -DCMAKE_POLICY_VERSION_MINIMUM=3.5 .. && make
 
    - name: Install Maven
      run: |
        apt-get update
        apt-get install -y maven
    - name: Get version
      id: get_version
      run: echo "VERSION=$(cat bindings/java/version.txt)" >> $GITHUB_ENV
      shell: bash

    - name: Download Artifacts
      uses: actions/download-artifact@v4  # updated from v3
      with:
        name: manifold_java_bindings_mac_${{env.VERSION}}
        path: mac-jar

    - name: Setup libraries
      shell: bash
      run: |
        VERSION=$(cat bindings/java/version.txt)
        mkdir -p ./bindings/java/target/classes/
        cp -r mac-jar/* ./bindings/java/target/classes/
        find . -name "*.jar"
        find . -name "*.dylib"
        find . -name "*.so"
        
    - name: Make Jar
      shell: bash
      run: |
        VERSION=$(cat ./bindings/java/version.txt)
        echo "linux_jar_file=./bindings/java/target/manifold3d-cross-platform-$VERSION.jar" >> $GITHUB_ENV
        cd ./bindings/java
        mvn versions:set -DnewVersion=$VERSION --file pom.xml
        mvn package -Dos.classifier=linux-x86_64
        cd ../../
        find . -name "*.jar"
        mv ./bindings/java/target/manifold3d-*.jar ${{env.linux_jar_file}}
    - name: Upload artifact
      uses: actions/upload-artifact@v4  # updated from v3
      with:
        name: manifold_java_bindings_linux_${{env.VERSION}}
        path: ./bindings/java/target/manifold3d-cross-platform-$VERSION.jar
    - name: Deploy Jar
      shell: bash
      run: |
        mvn deploy:deploy-file \
          -DpomFile=bindings/java/pom.xml \
          -DrepositoryId=clojars \
          -Durl=https://clojars.org/repo \
          -DgroupId=com.github.madhephaestus \
          -DartifactId=manifold3d \
          -Dversion=$VERSION \
          -Dpackaging=jar \
          -Dfile=${{env.linux_jar_file}} \
          -Dclassifier=cross-platform-$VERSION  \
          -Dfiles=$linux_jar_file \
          -Dclassifiers=cross-platform-$VERSION  \
          -Dtypes=jar \
          --settings=bindings/java/settings.xml
      env:
        CLOJARS_PASSPHRASE: ${{ secrets.CLOJARS_PASSPHRASE }}
        CLOJARS_TOKEN: ${{ secrets.CLOJARS_TOKEN }}

    
